resolve_var() {
  local val="${!1}"
  if [[ "${!val+x}" ]]; then
    echo "${!val}"
  else
    echo "$val"
  fi
}

SELECTED_SERVICE=$(cat ${TARGET_FILE:-/app/.aws/selected_service})

VAR_NAME="${SELECTED_SERVICE}_NAME"
VAR_REGION="${SELECTED_SERVICE}_REGION"
VAR_ROLE="${SELECTED_SERVICE}_ROLE"
VAR_SSM_TARGET="${SELECTED_SERVICE}_SSM_TARGET"
VAR_SSM_DOCUMENT_NAME="${SELECTED_SERVICE}_SSM_DOCUMENT_NAME"
VAR_SSM_HOST="${SELECTED_SERVICE}_SSM_HOST"
VAR_SSM_HOST_PORT="${SELECTED_SERVICE}_SSM_HOST_PORT"
VAR_SSM_CLIENT_PORT="${SELECTED_SERVICE}_SSM_CLIENT_PORT"
VAR_DB_USER="${SELECTED_SERVICE}_DB_USER"
VAR_DB_NAME="${SELECTED_SERVICE}_DB_NAME"

SERVICE_NAME=$(resolve_var "$VAR_NAME")
SERVICE_REGION=$(resolve_var "$VAR_REGION")
SERVICE_ROLE=$(resolve_var "$VAR_ROLE")
SERVICE_SSM_TARGET=$(resolve_var "$VAR_SSM_TARGET")
SERVICE_SSM_DOCUMENT_NAME=$(resolve_var "$VAR_SSM_DOCUMENT_NAME")
SERVICE_SSM_HOST=$(resolve_var "$VAR_SSM_HOST")
SERVICE_SSM_HOST_PORT=$(resolve_var "$VAR_SSM_HOST_PORT")
SERVICE_SSM_CLIENT_PORT=$(resolve_var "$VAR_SSM_CLIENT_PORT")
SERVICE_DB_USER=$(resolve_var "$VAR_DB_USER")
SERVICE_DB_NAME=$(resolve_var "$VAR_DB_NAME")

export SELECTED_SERVICE
export SERVICE_NAME
export SERVICE_REGION
export SERVICE_ROLE
export SERVICE_SSM_TARGET
export SERVICE_SSM_DOCUMENT_NAME
export SERVICE_SSM_HOST
export SERVICE_SSM_HOST_PORT
export SERVICE_SSM_CLIENT_PORT
export SERVICE_DB_USER
export SERVICE_DB_NAME
