#!/usr/bin/env bash

# Beispielwerte, die sonst aus der echten Datei kommen würden
SERVICES="DEV"
DEV_NAME="DevService"
DEV_REGION="eu-central-1"
DEV_ROLE="some-role"
DEV_SSM_TARGET="target-id"
DEV_SSM_DOCUMENT_NAME="doc"
DEV_SSM_HOST="host"
DEV_SSM_HOST_PORT="1234"
DEV_SSM_CLIENT_PORT="5678"

COLOR=""
SUCCESS_COLOR=""
ERROR_COLOR=""
NC=""
